# -*- coding: utf-8 -*-
"""ainewsgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj3NeQkLAs3y8ApEOYciE9DkTS4arCWb
"""

!pip install requests openai

import requests

API_KEY = "4ae008a61a494589b08ca76bc9afa71f"
url = f"https://newsapi.org/v2/top-headlines?country=us&apikey={API_KEY}"

response = requests.get(url)
data = response.json()

articles = data["articles"]

for article in articles[:5]:
    print(article["title"], article["description"])

!pip install transformers

from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM

# Initialize the summarization pipeline with a specific model
model_name = "sshleifer/distilbart-cnn-12-6"
summarizer = pipeline("text-generation", model=model_name, max_length=150, min_length=30, do_sample=False)

def summarize_news(text):
    # Access 'generated_text' directly from the result of the pipeline for text-generation task
    return summarizer(text[:1000])[0]['generated_text']

news_report = ""

for article in articles[:5]:
    summary = summarize_news(article["description"] or article["title"])

    news_report += f"""
    Title: {article['title']}
    Summary: {summary}
    Link: {article['url']}

    -----------------------
    """

import smtplib
from email.mime.text import MIMEText
from google.colab import userdata

EMAIL = "Isaiahakinlabi99@gmail.com"
PASSWORD = userdata.get('GMAIL_APP_PASSWORD') # Retrieve from Colab Secrets

msg = MIMEText(news_report)
msg["Subject"] = "Daily News Summary"
msg["From"] = EMAIL
msg["To"] = EMAIL

# Use SMTP_SSL for port 465 to establish an SSL-wrapped connection
with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
    server.login(EMAIL, PASSWORD)
    server.send_message(msg)

print("Email sent")

import os

NEWS_API_KEY = os.getenv("NEWS_API_KEY")
EMAIL = os.getenv("EMAIL")
PASSWORD = os.getenv("EMAIL_PASSWORD")